changelog:
  exclude:
    labels:
      - "duplicate"
      - "help wanted"
      - "invalid"
      - "question"
      - "wontfix"
  categories:
    - title: Added
      labels:
        - "enhancement"
    - title: Fixed
      labels:
        - "bug"
    - title: Documentation
      labels:
        - "documentation"
    - title: Dependencies
      labels:
        - "dependencies"
    - title: Other Changes
      labels:
        - "*"