version: '3.9'

secrets:
  NUXT_UI_PRO_LICENSE:
    environment: APP_NUXT_UI_PRO_LICENSE
  FORMKIT_PRO_KEY:
    environment: APP_FORMKIT_PRO_KEY

services:
  blog:
    container_name: blog
    build:
      context: .
      dockerfile: ./apps/Dockerfile
      args:
        - APP_NAME=@tituskirch/blog
        - APP_PATH=apps/blog
      secrets:
        - NUXT_UI_PRO_LICENSE
        - FORMKIT_PRO_KEY
    environment:
      - FORMKIT_PRO_KEY=${APP_FORMKIT_PRO_KEY}
      - NUXT_UI_PRO_LICENSE=${APP_NUXT_UI_PRO_LICENSE}
    restart: always
    ports:
      - 3001:3000
    networks:
      - app_network
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/Dockerfile
      args:
        - APP_NAME=@tituskirch/web
        - APP_PATH=apps/web
      secrets:
        - NUXT_UI_PRO_LICENSE
        - FORMKIT_PRO_KEY
    environment:
      - FORMKIT_PRO_KEY=${APP_FORMKIT_PRO_KEY}
      - NUXT_UI_PRO_LICENSE=${APP_NUXT_UI_PRO_LICENSE}
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./services/Dockerfile
      args:
        - SERVICE_NAME=@tituskirch/api
        - SERVICE_PATH=services/api
    entrypoint: php artisan octane:frankenphp --max-requests=1
    ports:
      - '8000:8000'

networks:
  app_network:
    driver: bridge
