version: '3'

services:
  blog:
    container_name: blog
    build:
      context: .
      dockerfile: ./apps/Dockerfile
      args:
        - PACKAGE_NAME=@repo/blog
        - PACKAGE_PATH=apps/blog
    restart: always
    ports:
      - 3001:3000
    networks:
      - app_network
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/Dockerfile
      args:
        - PACKAGE_NAME=@repo/web
        - PACKAGE_PATH=apps/web
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
