version: '3'

services:
  blog:
    container_name: blog
    build:
      context: .
      dockerfile: ./apps/Dockerfile
      args:
        - PACKAGE_NAME=@tituskirch/blog
        - PACKAGE_PATH=apps/blog
    environment:
      - FORMKIT_PRO_KEY=${APP_FORMKIT_PRO_KEY}
      - NUXT_UI_PRO_LICENSE=${APP_NUXT_UI_PRO_LICENSE}
    restart: always
    ports:
      - 3001:3000
    networks:
      - app_network
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/Dockerfile
      args:
        - PACKAGE_NAME=@tituskirch/web
        - PACKAGE_PATH=apps/web
    environment:
      - FORMKIT_PRO_KEY=${APP_FORMKIT_PRO_KEY}
      - NUXT_UI_PRO_LICENSE=${APP_NUXT_UI_PRO_LICENSE}
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
