
name: Docker app
description: Docker job for an app

inputs:
  app_name:
    description: "Name of the app"
    required: true
  push_image:
    description: "Push Docker image"
    required: false
    default: "false"
  docker_registry:
    description: "Docker registry"
    required: true
  docker_registry_username:
    description: "Docker registry username"
    required: true
  docker_registry_password:
    description: "Docker registry password"
    required: true
  docker_image_tag:
    description: "Docker image tag"
    required: false
    default: ""
  docker_image_tag_latest:
    description: "Docker image tag latest"
    required: false
    default: "false"
  
runs:
  using: "composite"
  steps:    
    - name: Login to GitHub container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.docker_registry }}
        username: ${{ inputs.docker_registry_username }}
        password: ${{ inputs.docker_registry_password }}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./apps/Dockerfile
        load: true
        tags: ${{ inputs.docker_registry }}/tituskirch/${{ inputs.app_name }}:test
        build-args: |
          PACKAGE_NAME=@tituskirch/${{ inputs.app_name }}
          PACKAGE_PATH=apps/${{ inputs.app_name }}
        cache-from: type=gha
        cache-to: type=local,mode=max,dest=/tmp/${{ inputs.app_name }}-docker-cache
      
    - name: Start Docker container
      shell: bash
      run: |
        docker run -d --rm -p 3000:3000 ${{ inputs.docker_registry }}/tituskirch/${{ inputs.app_name }}:test
      id: start_container

    - name: Wait for docker container to start
      shell: bash
      run: |
        counter=0
        while ! nc -z localhost 3000; do
            sleep 1
            counter=$((counter + 1))
            if [ $counter -ge 30 ]; then
                echo "Service didn't start within 30 seconds, exiting."
                exit 1
            fi
        done

    - name: Stop Docker container
      shell: bash
      if: success()
      run: |
        docker stop $(docker ps -q --filter ancestor="${{ inputs.docker_registry }}/tituskirch/${{ inputs.app_name }}:test")
  
    - name: Push Docker image
      if: inputs.push_image == 'true' && inputs.docker_image_tag != ''
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./apps/Dockerfile
        push: true
        tags: |
          ${{ inputs.docker_registry }}/tituskirch/${{ inputs.app_name }}:${{ inputs.docker_image_tag }}
          ${{ inputs.docker_image_tag_latest == "true" ? inputs.docker_registry + "/tituskirch/" + inputs.app_name + ":latest" : "" }}
        # platforms: linux/amd64,linux/arm64 (wait for arm workers and then ignore amd64)
        build-args: |
          PACKAGE_NAME=@tituskirch/${{ inputs.app_name }}
          PACKAGE_PATH=apps/${{ inputs.app_name }}
        cache-from: type=local,src=/tmp/${{ inputs.app_name }}-docker-cache
        cache-to: type=gha,mode=max