name: CI/CD

on:
  push:
    branches: ["main", "stage", "dev"]
    paths-ignore:
      - "docs/**"
      - "*.md"
  pull_request:
    branches: ["*"]
    paths-ignore:
      - "docs/**"
      - "*.md"

# remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  DOCKER_CONTAINER_REGISTRY: ghcr.io


jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

  lint-and-format:
    needs:
      - install-dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      - name: Enable corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Format
        run: pnpm format

  build:
    needs:
      - lint-and-format
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      - name: Enable corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Cache build
        uses: actions/upload-artifact@v4
        with:
          retention-days: 3
          name: build
          path: |
            apps/*/.nuxt
            packages/*/.nuxt

  test:
    needs:
      - build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      - name: Enable corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Restore build cache
        uses: actions/download-artifact@v4
        with:
          name: build
          path: |
            apps
            packages
          
      # - name: Test
      #   run: pnpm test

  test-e2e:
    needs:
      - build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      - name: Enable corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Restore build cache
        uses: actions/download-artifact@v4
        with:
          name: build
          path: |
            apps
            packages
          
      # - name: Test E2E
      #   run: pnpm test:e2e
  
  docker-apps-build:
    needs:
      - build
      # - test
      # - test-e2e
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        apps: [blog, web]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            apps:
              - 'apps/**'
              - 'packages/**'
  
      - name: Enable corepack
        if: steps.changes.outputs.apps == 'true'
        run: corepack enable

      - name: Setup node
        if: steps.changes.outputs.apps == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        if: steps.changes.outputs.apps == 'true'
        run: pnpm install

      - name: Restore build cache
        if: steps.changes.outputs.apps == 'true'
        uses: actions/download-artifact@v4
        with:
          name: build
          path: |
            apps
            packages
      
      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        if: steps.changes.outputs.apps == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        if: steps.changes.outputs.apps == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/Dockerfile
          # push: true
          # load: true
          tags: ${{ env.DOCKER_CONTAINER_REGISTRY }}/tituskirch/${{ matrix.apps }}:test
          build-args: |
            PACKAGE_NAME=@tituskirch/${{ matrix.apps }}
            PACKAGE_PATH=apps/${{ matrix.apps }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
        
      - name: Start Docker container
        if: steps.changes.outputs.apps == 'true'
        run: |
          docker run -d --rm -p 3000:3000 ${{ env.DOCKER_CONTAINER_REGISTRY }}/tituskirch/${{ matrix.apps }}:test
        id: start_container
        continue-on-error: true

      - name: Wait for docker container to start
        if: steps.changes.outputs.apps == 'true'
        run: |
          counter=0
          while ! nc -z localhost 3000; do
              sleep 1
              counter=$((counter + 1))
              if [ $counter -ge 30 ]; then
                  echo "Service didn't start within 30 seconds, exiting."
                  exit 1
              fi
          done

      - name: Stop Docker container
        if: steps.changes.outputs.apps == 'true' && success()
        run: docker stop $(docker ps -q --filter ancestor="${{ env.DOCKER_CONTAINER_REGISTRY }}/tituskirch/${{ matrix.apps }}:test")

      - name: Push Docker image
        if: steps.changes.outputs.apps == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/Dockerfile
          push: true
          tags: ${{ env.DOCKER_CONTAINER_REGISTRY }}/tituskirch/${{ matrix.apps }}:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            PACKAGE_NAME=@tituskirch/${{ matrix.apps }}
            PACKAGE_PATH=apps/${{ matrix.apps }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # todo: 2
  # - push in dev => update dev container (only needed)
  # push: ${{ github.event_name != 'pull_request' }}
  # - extra ci for (pre) release => on (pre) release in main/stage => update stage/prod container